export const initialState = {
    user : null,
    allUsers: null,
    allArtists: null,
    allSongs: null,
    allAlbums: null,
    userFilter: null,
    albumFilter: null,
    languageFilter: null,
    categoryFilter: "all",
    arlertType: null,
    isSongPlaying: false,
    songIndex: 0,
    isAlbumOpening: null,
    albumIndex: 0,
} 